name: Bug Report
description: Using Sparrow, but it's not working as you expect?
title: "[Bug]: "
labels: ["bug"]
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to fill out this bug report!

       ## **Before Submitting:**

       * Please search to make sure this issue has not been opened already.
       * If this is a question about how to integrate Sparrow with your project, please ask in our [Community forum](https://community.metamask.io/c/developer-questions/) instead. This will get your question answered more quickly and make it easier for other devs to find the answer in the future.
 - type: textarea
   id: what-happened
   attributes:
     label: Describe the bug
     description: What happened? What did you expect to happen? Please include screenshots if applicable!
     placeholder: Tell us what you see!
   validations:
     required: true
 - type: textarea
   id: reproduce
   attributes:
     label: Steps to reproduce
     description: List all steps needed to reproduce the problem
     value: |
       1.
   validations:
     required: true
 - type: textarea
   id: error
   attributes:
     label: Error messages or log output
     description: Please copy and paste any relevant error messages or log output. This will be automatically formatted, so there is no need for backticks.
     render: shell
 - type: input
   id: version
   attributes:
     label: Version
     description: What version of Sparrow are you running? You can find the version in "Settings" > "About"
   validations:
     required: true
 - type: dropdown
   id: build
   attributes:
     label: Build type
     description: Are you using a testing or development build of Sparrow? If so, please select the type of build you are using.
     options:
       - Beta
       - Flask
       - Other (please specify exactly where you obtained this build in "Additional Context" section)
 - type: dropdown
   id: browsers
   attributes:
     label: Browser
     description: Which browsers have you seen the problem on?
     multiple: true
     options:
       - Chrome
       - Firefox
       - Microsoft Edge
       - Brave
       - Other (please elaborate in the "Additional Context" section)
   validations:
     required: true
 - type: dropdown
   id: os
   attributes:
     label: Operating system
     description: Which operating systems have you seen the problem on?
     multiple: true
     options:
       - Windows
       - MacOS
       - Linux
       - Other (please elaborate in the "Additional Context" section)
   validations:
     required: true
 - type: dropdown
   id: hardware-wallet
   attributes:
     label: Hardware wallet
     description: Are you using any of these hardware wallets? Please include the firmware version in the "Additional context" section below for any that you select here.
     multiple: true
     options:
       - Ledger
       - Trezor
       - Keystone
       - GridPlus Lattice1
       - AirGap Vault
       - Other (please elaborate in the "Additional Context" section)
 - type: textarea
   id: additional
   attributes:
     label: Additional context
     description: Add any other context about the problem here, e.g. related issues, additional error messages or logs, or any potentially relevant details about the environment or situation the bug occurred in.
